---
# copy this file instead of symlinking
cops_app_name: djangoproject
cops_db_name: "{{cops_app_name}}"
cops_db_user: "{{cops_app_name}}"
cops_db_password: secret
cops_django_secret_key: verysupersecretlen64
cops_django_admin_password: secret
cops_django_pkg_python_slug: "3"
