---
# Remember to encrypt your vault with ansible-vault for non public env
makinastates_pillar: |
  ---
  {% set project_name = 'project' %}
  {% if not grains %}{% set grains = {} %}{% endif %}
  {% set fqdn = grains.get('fqdn', '{0}.local'.format(project_name)) %}
  {% set domains = [fqdn,
                    "{1}.{0}".format(fqdn, project_name),
                    "www.{0}".format(fqdn)] %}
  makina-projects.{{project_name}}:
    api_version: '2'
    data:
      #orig_py: /usr/bin/python3
      force_ssl: true
      use_vt: false
      domain: {{domains[0]}}
      server_aliases: {{domains[1:]}}
      admins:
        - admin: {mail: devnull@makina-corpus.com, password: admin}
      DJANGO_SETTINGS_MODULE: "{PROJECT}.settings.test"
      requirements: "{project_root}/requirements/test.txt"
      extra_settings: {}
      django_settings:
        ALLOWED_HOSTS: {{domains}}
        # ONLY FOR CI
        LOGGING:
          handlers:
            mail_admins:
              level: 'ERROR'
              class: 'logging.StreamHandler'
            console:
              level: 'ERROR'
          loggers:
            '':
              level: 'ERROR'
            django.request:
               level: 'ERROR'
            django:
               level: 'ERROR'
        DATABASES:
          default:
            HOST: localhost
            USER: db1
            NAME: db1
            PASSWORD: db1
      
# vim:set ft=sls:
