---
cops_django_db_user: "{{cops_db_user}}"
cops_django_db_name: "{{cops_db_name}}"
cops_django_db_password: "{{cops_db_password}}"
cops_postgresql___roles:
- name: "{{cops_django_db_user}}"
  password: "{{cops_django_db_password}}"
  # for mysql
  # privs: "{{cops_django_db_name}}.*:ALL"
cops_postgresql__databases:
- db: "{{cops_django_db_name}}"
  # for pgsql
  owner: "{{cops_django_db_user}}"
cops_django_name: "{{cops_app_name}}"
pureftpd_servers: django_servers
django_servers: django_servers
db_backup_servers: db_backup_servers
dbsmartbackup_servers: db_backup_servers
postgresql_servers: postgresql_servers
mysql_servers: mysql_servers
db_servers: "{{cops_django_db_role_type[cops_django_db_type]}}_servers"
app_servers: "{{django_servers}}"
#
cops_installer_mode: lazy
cops_django_nginx_port: 80
cops_django_nginx_ssl_port: 443
corpusops_nginx_default_vhost_port: "{{cops_django_nginx_port}}"
corpusops_nginx_default_vhost_ssl_port: "{{cops_django_nginx_ssl_port}}"
cops_postgresql_s_setup_server_postgis: "{{'postgis' in cops_django_db_type}}"
cops_django_db_type: django.db.backends.postgresql_psycopg2
cops_django_dbsmartbackup_types:
  django.db.backends.postgresql_psycopg2: "postgresql"
  django.contrib.gis.db.backends.postgis: "postgresql"
  django.db.backends.mysql: "mysql"
  django.db.backends.sqlite3: null
cops_django_dbsmartbackup_type: "{{cops_django_dbsmartbackup_types[cops_django_db_type]}}"
cops_django_db_role_type:
  django.db.backends.postgresql_psycopg2: "postgresql"
  django.contrib.gis.db.backends.postgis: "postgresql"
  django.db.backends.mysql: null
  django.db.backends.sqlite3: null
cops_django_db_role: "{{cops_django_db_role_type[cops_django_db_type]}}"
# vim:set ft=sls:
