---
# THIS SHOULD RESIDE IN AN ENCRYPTED VAULT
cops_db_name: db
cops_db_user: user
cops_db_password: secret
cops_django_secret_key: verysupersecret
cops_django_admin_password: secret
#cops_pureftpd_ftp_users: []
# see .ansible/playbooks/roles/django_vars/defaults/main.yml [cops_pureftpd_ftp_users]
cops_deploy_ssh_key_paths:
  staging:
    path: "{{'local/.ssh/deploy_staging'|copsf_abspath}}"
    pub: |-
      ssh-rsa AAAAxxx== myapp@staging
    private: |-
      -----BEGIN RSA PRIVATE KEY-----
      yyy==
      -----END RSA PRIVATE KEY-----
