#!/usr/bin/env bash
# {{ansible_managed}}
# {% set d = cops_django_vars %}
set -ex
export ENTRY_POINT="${IMAGE_ENTRY_POINT-{{d.ep_main_ep}}}"
if [ ! -e /setup ];then mkdir -p "/setup";fi
if [ -d /setup/rootfs ];then
    rsync -azv /setup/rootfs/ /
fi
if [[ -n "$A_RECONFIGURE" ]];then
    echo "$A_RECONFIGURE" > /setup/env.reconfigure.yml
    chmod 600 /setup/env.reconfigure.yml
elif [ ! -e /setup/env.reconfigure.yml ];then
    rm -f /setup/env.reconfigure.yml
fi
if [[ -n "$A_POSTCONFIGURE" ]];then
    echo "$A_POSTCONFIGURE" > /setup/env.postconfigure.yml
    chmod 600 /setup/env.postconfigure.yml
elif [ ! -e /setup/env.postconfigure.yml ];then
    rm -f /setup/env.postconfigure.yml
fi
if [[ -n "${TEST_LOOP-}" ]];then
    while true;do sleep 60;done
fi
# Launch dance (generally systemd which in turn launch app)
cd /
if [[ -z ${SKIP_PRECONFIGURE-} ]];then
    # The script will be certainly reexecuted a second time from
    # systemd (with different arguments
    "{{d.reconfigure}}" reconfigure.yml env.reconfigure.yml
fi
if [[ -z ${SKIP_START-} ]];then
    exec "$ENTRY_POINT" $@
fi
