---
- when: ["cops_django_s_workers_service"]
  tags: ["cops_django_s_workers_service"]
  block:
  # activate the main app service
  - cops_service:
      state: "{{cops_django_vars.activated | ternary('started', 'stopped')}}"
      enabled: "{{cops_django_vars.activated | ternary(True, False)}}"
      daemon_reload: yes
      name: "{{item}}"
    with_items: "{{cops_django_vars.services}}"
  # this will fail on non systemd hosts on purpose !
  # if we have activated the reconfigure units (docker mode essentially)
  - cops_service:
      enabled: "{{cops_django_vars.activated | ternary(True, False)}}"
      daemon_reload: yes
      name: "{{item}}"
    with_items: "{{cops_django_vars.reconfigure_services}}"
    when: corpusops_vars.has_services_manager
  # force a reload/restart here
  - shell: echo "force service reload/restart"
    notify: "{{cops_django_vars.rhandlers}}"
  - meta: flush_handlers
