sudo: false
language: python
python:
    - "3.5"
addons:
    postgresql: "9.4"
env:
    - TOXENV=pylama
    - TOXENV=isort
    - TOXENV=docs
    - TOXENV=py27-coverage
    - TOXENV=py27-reverse
    - TOXENV=py34
    - TOXENV=py34-reverse
    - TOXENV=py35
    - TOXENV=py35-reverse
install:
    - pip install coveralls tox
before_script:
    - createuser -U postgres -d makina
    - createdb -U postgres -O makina makina
    - cp src/*/settings/local.py.dist   $(ls src/*/settings/local.py.dist|sed "s/\.dist//g")
    - sed -i -re 's/<DB_NAME>/makina/g' $(ls src/*/settings/local.py.dist|sed "s/\.dist//g")
    - sed -i -re 's/<DB_USER>/makina/g' $(ls src/*/settings/local.py.dist|sed "s/\.dist//g")
script:
    - tox
after_success:
    - coveralls
