ARG DOCKER_IMAGE
FROM ${DOCKER_IMAGE}-stage0
ENV DOCKER_IMAGE=${DOCKER_IMAGE}-stage1
RUN for i in DOCKER_IMAGE;do\
    eval ': ${'$i':?Please provide --build-arg=$i}' >&2;done
WORKDIR /provision_dir
ADD . .
RUN ROLES="django_push_code django_layout django_fixperms" $_cr
RUN ROLES="django_setup_venv" $_cr

# Default to launch systemd, and you ll have have to mount:
#  -v /sys/fs/cgroup:/sys/fs/cgroup:ro
STOPSIGNAL SIGRTMIN+3
CMD ["/entry_point"]
