---
- when: [cops_django_s_prerequisites_pkgs]
  tags: [cops_django_s_prerequisites_pkgs]
  block:
  # workaround the libjpegturbo transitional
  # package hell by installing it explicitly
  - name: update & install libjpeg-dev (workaround for deb bug)
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['debian'])"
    with_items: [libjpeg-dev]
  - name: update & install prerequisites
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['debian'] and
            cops_django_vars.deb_packages is not none and
            cops_django_vars.deb_packages|length > 0)"
    with_items: "{{cops_django_vars.deb_packages}}"
  - name: update & install prerequisites
    package:
      update_cache: yes
      enablerepo: epel,epel-testing
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['redhat'] and
            cops_django_vars.rh_packages is not none and
            cops_django_vars.rh_packages|length > 0)"
    with_items: "{{cops_django_vars.rh_packages}}"
  - name: update & install prerequisites (venv)
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['debian'] and
            cops_django_vars.venv_deb_packages is not none and
            cops_django_vars.venv_deb_packages|length > 0)"
    with_items: "{{cops_django_vars.venv_deb_packages}}"
  - name: update & install prerequisites (venv)
    package:
      update_cache: yes
      enablerepo: epel,epel-testing
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['redhat'] and
            cops_django_vars.venv_rh_packages is not none and
            cops_django_vars.venv_rh_packages|length > 0)"
    with_items: "{{cops_django_vars.venv_rh_packages}}"
- when: [cops_django_s_prerequisites_build_pkgs]
  tags: [cops_django_s_prerequisites_build_pkgs]
  block:
  - name: update & install build prerequisites
    package:
      cache_valid_time: '{{60*60}}'
      update_cache: yes
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['debian'] and
            cops_django_vars.deb_build_packages is not none and
            cops_django_vars.deb_build_packages|length > 0)"
    with_items: "{{cops_django_vars.deb_build_packages}}"
  - name: update & install build prerequisites
    package:
      update_cache: yes
      enablerepo: epel,epel-testing
      name: '{{item}}'
      state: present
    when: "(ansible_os_family.lower() in ['redhat'] and
            cops_django_vars.rh_build_packages is not none and
            cops_django_vars.rh_build_packages|length > 0)"
    with_items: "{{cops_django_vars.rh_build_packages}}"
- include_role: {name: corpusops.roles/localsettings_supervisor}
  when: [cops_django_s_prerequisites_supervisor]
  tags: [cops_django_s_prerequisites_supervisor]
