---
- environment:
     CFLAGS: "-I/usr/include/gdal"
  block:
    - stat: {path: "{{requirements}}"}
      register: cops_c_django_venv_req
    - when: cops_c_django_venv_req.stat.exists
      pip:
        requirements: "{{requirements}}"
        state: present
        virtualenv: "{{cops_django_vars.py_root}}"
        virtualenv_python: "{{(
          (cops_django_vars.build_py and
          '{0}/bin/python'.format(cops_django_vars.py_inst)) or
          cops_django_vars.get('orig_py', None) or
          '/usr/bin/python{0}'.format(cops_django_vars.py_ver))}}"
        virtualenv_command: "{{(
          cops_django_vars.build_py and
          '{0}/bin/virtualenv'.format(cops_django_vars.py_inst) or
          cops_django_vars.get('venv_bin', 'virtualenv'))}}"
        virtualenv_site_packages: "{{cops_django_vars.venv_site_packages}}"
    - shell: |
        {% set data = cops_django_vars%}
        cd "{{data.project_root}}"
        if [ -e "{{data.py_root}}/bin/activate" ];then . "{{data.py_root}}/bin/activate";fi
        if [ -e setup.py ];then pip install -e .;fi
      changed_when: false
