---
- hosts: "{{db_servers|default('all')}}"
  tasks:
  - tags: [cops_django_lifecycle_db]
    when: "cops_django_lifecycle_db|default(true)"
    block:
    - include_role: {name: django_db_vars}
  - set_fact:
      cops_postgresql_do_install_postgis: "{{vars['cops_django_db_has_postgis']}}"

- import_playbook: "/provision_dir/local/setups.{{cops_django_db_role}}/.ansible/playbooks/site.yml"
  tags: [cops_django_lifecycle_db]
  when: "cops_django_lifecycle_db|default(true)"

