---
# FTP
- hosts: "{{pureftpd_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - when: ["cops_django_lifecycle_ftp|default(true)"]
    tags: ["cops_django_lifecycle_ftp"]
    block:
    - include_role: {name: django_vars,   allow_duplicates: false}
- import_playbook: "../../local/setups.pureftpd/.ansible/playbooks/site.yml"
  when: ["cops_django_lifecycle_ftp|default(true)"]
  tags: ["cops_django_lifecycle_ftp"]
