---
- include_role: {name: django_vars, allow_duplicates: false}
- set_fact:
    cacheable: false
    cops_django_lifecycle_app: |-
     ((not vars.get('SKIP_INSTALL_DJANGO', False) and
       (cops_django_lifecycle_app|default(false))) or
      vars.get('FORCE_INSTALL_DJANGO', False))
