---
- file:
    state: directory
    path: "{{home}}"
    owner: "{{sysuser|default('root')}}"
    group: "{{sysgroup|default('root')}}"
    mode: "{{mode|default('2771')}}"
- shell: mktemp
  register: mytempfile
- name: "configure pureftpd virtualuser {{user}} -> {{sysuser}}:{{sysgroup}}"
  template:
    src: "../templates/ftpuser.sh"
    dest: "{{corpusops_services_ftp_pureftpd_vars.prefix}}/user_{{user}}"
    mode: "0700"
- name: "configure pureftpd virtualuser {{user}} -> {{sysuser}}:{{sysgroup}}"
  shell: "{{corpusops_services_ftp_pureftpd_vars.prefix}}/user_{{user}}"

