---
- shell: pure-pw mkdb
- copy:
    dest: "{{corpusops_services_ftp_pureftpd_vars.prefix}}/conf/PassivePortRange"
    force: true
    content: "{{cops_django_vars.ftp_port_range}}"
  when: "cops_django_vars.ftp_port_range|copsf_bool"
- copy:
    dest: "{{corpusops_services_ftp_pureftpd_vars.prefix}}/conf/ForcePassiveIP"
    force: true
    content: "{{cops_django_vars.ftp_ip}}"
  when: "(
          cops_django_vars.get('ftp_domain',
          cops_django_vars.get('ftp_ip', ''))
         )|copsf_asbool"
- file:
    path: "{{corpusops_services_ftp_pureftpd_vars.prefix}}/conf/ForcePassiveIP"
    state: absent
  when: "not (
          cops_django_vars.get('ftp_domain',
          cops_django_vars.get('ftp_ip', ''))
         )|copsf_bool"
- file:
    path: "{{corpusops_services_ftp_pureftpd_vars.prefix}}/conf/PassivePortRange"
    state: absent
  when: "not (cops_django_vars.ftp_port_range|copsf_bool)"
- cops_service:
    state: "restarted"
    enabled: true
    daemon_reload: yes
    name: "pure-ftpd"
