---
- include_jinja_vars:
    content: |-
      {% set r = {} %}
      {% set _ = r.update({'only_steps': only_steps|default(False)}) %}
      {% set only_steps = r['only_steps'] %}
      #
      {% set _ = r.update({'cops_django_s_docker_reconfigure': cops_django_s_docker_reconfigure|default(False)}) %}
      {% set cops_django_s_docker_reconfigure = r['cops_django_s_docker_reconfigure'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_db':       cops_django_lifecycle_db      |default(not only_steps)}) %}
      {% set cops_django_lifecycle_db = r['cops_django_lifecycle_db'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_ftp':      cops_django_lifecycle_ftp     |default(False)}) %}
      {% set cops_django_lifecycle_ftp = r['cops_django_lifecycle_ftp'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_dbbackup': cops_django_lifecycle_dbbackup|default(not only_steps)}) %}
      {% set cops_django_lifecycle_dbbackup = r['cops_django_lifecycle_dbbackup'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_app_push_code':  cops_django_lifecycle_app_push_code               |default(not only_steps)}) %}
      {% set cops_django_lifecycle_app_push_code = r['cops_django_lifecycle_app_push_code'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_venv_venv':         cops_django_s_setup_venv_venv        |default(cops_django_s_setup_venv|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_venv_venv = r['cops_django_s_setup_venv_venv'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_venv_buildpy':      cops_django_s_setup_venv_buildpy     |default(cops_django_s_setup_venv|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_venv_buildpy = r['cops_django_s_setup_venv_buildpy'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_venv_requirements': cops_django_s_setup_venv_requirements|default(cops_django_s_setup_venv|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_venv_requirements = r['cops_django_s_setup_venv_requirements'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_front_sync':                   cops_django_s_setup_front_sync |default(cops_django_s_setup_front|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_front_sync = r['cops_django_s_setup_front_sync'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_front_build_yarn_install':     cops_django_s_setup_front_build_yarn_install    |default(cops_django_s_setup_front_build|default(cops_django_s_setup_front|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_django_s_setup_front_build_yarn_install = r['cops_django_s_setup_front_build_yarn_install'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_front_build_yarn_extra_steps': cops_django_s_setup_front_build_yarn_extra_steps|default(cops_django_s_setup_front_build|default(cops_django_s_setup_front|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_django_s_setup_front_build_yarn_extra_steps = r['cops_django_s_setup_front_build_yarn_extra_steps'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_front_build_yarn_build':       cops_django_s_setup_front_build_yarn_build      |default(cops_django_s_setup_front_build|default(cops_django_s_setup_front|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_django_s_setup_front_build_yarn_build = r['cops_django_s_setup_front_build_yarn_build'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_front_build':  (cops_django_s_setup_front_build_yarn_install or cops_django_s_setup_front_build_yarn_extra_steps or cops_django_s_setup_front_build_yarn_build)}) %}
      {% set cops_django_s_setup_front_build = r['cops_django_s_setup_front_build'] %}
      #
      {% set _ = r.update({'cops_django_s_prerequisites_pkgs': cops_django_s_prerequisites_pkgs            |default(cops_django_s_prerequisites|default(cops_django_lifecycle_app_prerequisites|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_prerequisites_pkgs = r['cops_django_s_prerequisites_pkgs'] %}
      #
      {% set _ = r.update({'cops_django_s_prerequisites_supervisor': cops_django_s_prerequisites_supervisor|default(cops_django_s_prerequisites|default(cops_django_lifecycle_app_prerequisites|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_prerequisites_supervisor = r['cops_django_s_prerequisites_supervisor'] %}
      #
      {% set _ = r.update({'cops_django_s_prerequisites_build_pkgs': cops_django_s_prerequisites_build_pkgs|default(cops_django_s_prerequisites|default(cops_django_lifecycle_app_prerequisites|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_prerequisites_build_pkgs = r['cops_django_s_prerequisites_build_pkgs'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_configs':    cops_django_s_setup_configs                                                                           |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_setup_configs = r['cops_django_s_setup_configs'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_hosts':      cops_django_s_setup_hosts                                                                             |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_setup_hosts = r['cops_django_s_setup_hosts'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_app':        cops_django_s_setup_app                                                                               |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_setup_app = r['cops_django_s_setup_app'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_supervisor': cops_django_s_setup_supervisor                                                                        |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_setup_supervisor = r['cops_django_s_setup_supervisor'] %}
      #
      {% set _ = r.update({'cops_django_s_layout_layout':  cops_django_s_layout_layout|default(cops_django_s_layout       |default(cops_django_lifecycle_app_layout|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_django_s_layout_layout = r['cops_django_s_layout_layout'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_reverse_proxy_dvhost':      cops_django_s_setup_reverse_proxy_dvhost     |default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_reverse_proxy_dvhost = r['cops_django_s_setup_reverse_proxy_dvhost'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_reverse_proxy_vhost':       cops_django_s_setup_reverse_proxy_vhost      |default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_reverse_proxy_vhost = r['cops_django_s_setup_reverse_proxy_vhost'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_reverse_proxy_front_vhost': cops_django_s_setup_reverse_proxy_front_vhost|default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_reverse_proxy_front_vhost = r['cops_django_s_setup_reverse_proxy_front_vhost'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_reverse_proxy_users':       cops_django_s_setup_reverse_proxy_users      |default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_django_s_setup_reverse_proxy_users = r['cops_django_s_setup_reverse_proxy_users'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_django_statics': cops_django_s_setup_django_statics|default(cops_django_s_setup_django|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_setup_django_statics = r['cops_django_s_setup_django_statics'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_django_locales': cops_django_s_setup_django_locales|default(cops_django_s_setup_django|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_setup_django_locales = r['cops_django_s_setup_django_locales'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_venv': ( cops_django_s_setup_venv_venv or cops_django_s_setup_venv_buildpy or cops_django_s_setup_venv_requirements)}) %}
      {% set cops_django_s_setup_venv = r['cops_django_s_setup_venv'] %}
      #
      {% set _ = r.update({'cops_django_s_reverse_proxy_install':                  cops_django_s_reverse_proxy_install                               |default(cops_django_s_reverse_proxy|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_reverse_proxy_install = r['cops_django_s_reverse_proxy_install'] %}
      #
      {% set _ = r.update({'cops_django_s_reverse_proxy_reload':                   cops_django_s_reverse_proxy_reload                                |default(cops_django_s_reverse_proxy|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_reverse_proxy_reload = r['cops_django_s_reverse_proxy_reload'] %}
      #
      {% set _ = r.update({'cops_django_s_manage_content_migrate':                 cops_django_s_manage_content_migrate                              |default(cops_django_s_manage_content|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_manage_content_migrate = r['cops_django_s_manage_content_migrate'] %}
      #
      {% set _ = r.update({'cops_django_s_manage_content_create_admins':           cops_django_s_manage_content_create_admins                        |default(cops_django_s_manage_content|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_manage_content_create_admins = r['cops_django_s_manage_content_create_admins'] %}
      #
      {% set _ = r.update({'cops_django_s_manage_content_syncdb_only_first_time':  cops_django_s_manage_content_syncdb_only_first_time               |default(cops_django_s_manage_content|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_manage_content_syncdb_only_first_time = r['cops_django_s_manage_content_syncdb_only_first_time'] %}
      #
      {% set _ = r.update({'cops_django_s_manage_content_reset_site':              cops_django_s_manage_content_reset_site                           |default(False)}) %}
      {% set cops_django_s_manage_content_reset_site = r['cops_django_s_manage_content_reset_site'] %}
      #
      {% set _ = r.update({'cops_django_s_manage_content_syncdb':              cops_django_s_manage_content_syncdb                           |default(False)}) %}
      {% set cops_django_s_manage_content_syncdb = r['cops_django_s_manage_content_syncdb'] %}
      #
      {% set _ = r.update({'cops_django_s_workers_service': cops_django_s_workers_service |default(cops_django_s_workers|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_workers_service = r['cops_django_s_workers_service'] %}
      #
      {% set _ = r.update({'cops_django_s_healthchecks':  cops_django_s_healthchecks  |default(cops_django_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_django_s_healthchecks = r['cops_django_s_healthchecks'] %}
      #
      {% set _ = r.update({'cops_django_s_fixperms_configs':   cops_django_s_fixperms_configs|default((cops_django_s_first_fixperms|default(not only_steps)) or (cops_django_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_django_s_fixperms_configs = r['cops_django_s_fixperms_configs'] %}
      #
      {% set _ = r.update({'cops_django_s_fixperms_run':       cops_django_s_fixperms_run    |default((cops_django_s_first_fixperms|default(not only_steps)) or (cops_django_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_django_s_fixperms_run = r['cops_django_s_fixperms_run'] %}
      #
      {% set _ = r.update({'cops_django_s_first_fixperms': cops_django_s_first_fixperms        |default(not only_steps)}) %}
      {% set cops_django_s_first_fixperms = r['cops_django_s_first_fixperms'] %}
      #
      {% set _ = r.update({'cops_django_s_end_fixperms':   cops_django_s_end_fixperms          |default(not only_steps)}) %}
      {% set cops_django_s_end_fixperms = r['cops_django_s_end_fixperms'] %}
      #
      {% set _ = r.update({'cops_django_s_entry_point_configs':  cops_django_s_entry_point_configs    |default(cops_django_s_entry_point|default(cops_django_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_django_s_entry_point_configs = r['cops_django_s_entry_point_configs'] %}
      #
      {% set _ = r.update({'cops_django_s_entry_point_services':  cops_django_s_entry_point_services  |default(cops_django_s_entry_point|default(cops_django_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_django_s_entry_point_services = r['cops_django_s_entry_point_services'] %}
      #
      {% set _ = r.update({'cops_django_s_users_user':     cops_django_s_users_user |default(cops_django_s_first_fixperms or cops_django_s_end_fixperms or cops_django_lifecycle_app_push_code or cops_django_s_users|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_users_user = r['cops_django_s_users_user'] %}
      #
      {% set _ = r.update({'cops_django_s_users_group':    cops_django_s_users_group|default(cops_django_s_first_fixperms or cops_django_s_end_fixperms or cops_django_lifecycle_app_push_code or cops_django_s_users|default(cops_django_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_django_s_users_group = r['cops_django_s_users_group'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_django':       ( cops_django_s_setup_django_statics or cops_django_s_setup_django_locales)}) %}
      {% set cops_django_s_setup_django = r['cops_django_s_setup_django'] %}
      #
      {% set _ = r.update({'cops_django_s_manage_content':       ( cops_django_s_manage_content_syncdb or cops_django_s_manage_content_migrate or cops_django_s_manage_content_create_admins or cops_django_s_manage_content_syncdb_only_first_time or cops_django_s_manage_content_reset_site)}) %}
      {% set cops_django_s_manage_content = r['cops_django_s_manage_content'] %}
      #
      {% set _ = r.update({'cops_django_s_users':          cops_django_s_users_user or cops_django_s_users_group}) %}
      {% set cops_django_s_users = r['cops_django_s_users'] %}
      #
      {% set _ = r.update({'cops_django_s_layout':         cops_django_s_layout_layout}) %}
      {% set cops_django_s_layout = r['cops_django_s_layout'] %}
      #
      {% set _ = r.update({'cops_django_s_prerequisites':  ( cops_django_s_prerequisites_supervisor or cops_django_s_prerequisites_build_pkgs or cops_django_s_prerequisites_pkgs)}) %}
      {% set cops_django_s_prerequisites = r['cops_django_s_prerequisites'] %}
      #
      {% set _ = r.update({'cops_django_s_workers':        cops_django_s_workers       |default(cops_django_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_django_s_workers = r['cops_django_s_workers'] %}
      #
      {% set _ = r.update({'cops_django_s_entry_point':    (cops_django_s_entry_point_configs or cops_django_s_entry_point_services)}) %}
      {% set cops_django_s_entry_point = r['cops_django_s_entry_point'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_front':  ( cops_django_s_setup_front_build or cops_django_s_setup_front_sync)}) %}
      {% set cops_django_s_setup_front = r['cops_django_s_setup_front'] %}
      #
      {% set _ = r.update({'cops_django_s_setup_reverse_proxy':  ( cops_django_s_setup_reverse_proxy_dvhost or cops_django_s_setup_reverse_proxy_vhost or cops_django_s_setup_reverse_proxy_users)}) %}
      {% set cops_django_s_setup_reverse_proxy = r['cops_django_s_setup_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_django_s_reverse_proxy':  (cops_django_s_reverse_proxy_reload or cops_django_s_reverse_proxy_install)}) %}
      {% set cops_django_s_reverse_proxy = r['cops_django_s_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_django_s_setup': ( cops_django_s_setup_configs or cops_django_s_setup_supervisor or cops_django_s_setup_venv or cops_django_s_setup_front or cops_django_s_setup_hosts or cops_django_s_setup_app or cops_django_s_setup_django or cops_django_s_setup_reverse_proxy)}) %}
      {% set cops_django_s_setup = r['cops_django_s_setup'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_app_level_1_steps': ( cops_django_s_users or cops_django_s_layout or cops_django_s_first_fixperms or cops_django_s_prerequisites or cops_django_s_setup or cops_django_s_reverse_proxy or cops_django_s_workers or cops_django_s_healthchecks or cops_django_s_entry_point or cops_django_s_manage_content or cops_django_s_end_fixperms)}) %}
      {% set cops_django_lifecycle_app_level_1_steps = r['cops_django_lifecycle_app_level_1_steps'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_app_setup': cops_django_lifecycle_app_setup|default( (cops_django_lifecycle_app|default(False)) or ( cops_django_lifecycle_app_level_1_steps))}) %}
      {% set cops_django_lifecycle_app_setup = r['cops_django_lifecycle_app_setup'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_app': cops_django_lifecycle_app|default(cops_django_lifecycle_app_push_code or cops_django_lifecycle_app_setup)}) %}
      {% set cops_django_lifecycle_app = r['cops_django_lifecycle_app'] %}
      #
      {% set _ = r.update({'cops_django_lifecycle_lc_1_steps': ( cops_django_lifecycle_ftp or cops_django_lifecycle_db or cops_django_lifecycle_dbbackup or cops_django_lifecycle_app)}) %}
      {% set cops_django_lifecycle_lc_1_steps = r['cops_django_lifecycle_lc_1_steps'] %}
      #
      {% set _ = r.update({'cops_django_s_vars': cops_django_s_vars|default(cops_django_lifecycle_lc_1_steps) or only_steps}) %}
      {% set cops_django_s_vars = r['cops_django_s_vars'] %}
      #
      {{ r | to_json }}
