---
- set_fact:
    cacheable: false
    only_steps: "{{only_steps|default(False)}}"
- set_fact:
    cops_django_lifecycle_db:       "{{cops_django_lifecycle_db      |default(not only_steps)}}"
    cops_django_lifecycle_ftp:      "{{cops_django_lifecycle_ftp     |default(False)}}"
    cops_django_lifecycle_dbbackup: "{{cops_django_lifecycle_dbbackup|default(not only_steps)}}"
    cacheable: false
- set_fact:
    cacheable: false
    cops_django_s_setup_venv_venv:         "{{cops_django_s_setup_venv_venv        |default(cops_django_s_setup_venv|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_venv_buildpy:      "{{cops_django_s_setup_venv_buildpy     |default(cops_django_s_setup_venv|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_venv_requirements: "{{cops_django_s_setup_venv_requirements|default(cops_django_s_setup_venv|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_front_build_yarn_install:     "{{cops_django_s_setup_front_build_yarn_install    |default(cops_django_s_setup_front_build|default(cops_django_s_setup_front|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}}"
    cops_django_s_setup_front_build_yarn_extra_steps: "{{cops_django_s_setup_front_build_yarn_extra_steps|default(cops_django_s_setup_front_build|default(cops_django_s_setup_front|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}}"
    cops_django_s_setup_front_build_yarn_build:       "{{cops_django_s_setup_front_build_yarn_build      |default(cops_django_s_setup_front_build|default(cops_django_s_setup_front|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}}"
- set_fact:
    cacheable: false
    cops_django_s_setup_front_build:  "{{(cops_django_s_setup_front_build_yarn_install or
                                        cops_django_s_setup_front_build_yarn_extra_steps or
                                        cops_django_s_setup_front_build_yarn_build)}}"
    cops_django_s_prerequisites_pkgs: "{{cops_django_s_prerequisites_pkgs            |default(cops_django_s_prerequisites|default(cops_django_lifecycle_app_prerequisites|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_prerequisites_supervisor: "{{cops_django_s_prerequisites_supervisor|default(cops_django_s_prerequisites|default(cops_django_lifecycle_app_prerequisites|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_prerequisites_build_pkgs: "{{cops_django_s_prerequisites_build_pkgs|default(cops_django_s_prerequisites|default(cops_django_lifecycle_app_prerequisites|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_front_sync: "{{cops_django_s_setup_front_sync|default(cops_django_s_setup_front                                      |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_configs:    "{{cops_django_s_setup_configs                                                                           |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_setup_hosts:      "{{cops_django_s_setup_hosts                                                                             |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_setup_app:        "{{cops_django_s_setup_app                                                                               |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_setup_supervisor: "{{cops_django_s_setup_supervisor                                                                        |default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_layout_layout:  "{{cops_django_s_layout_layout|default(cops_django_s_layout       |default(cops_django_lifecycle_app_layout|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps)))))}}"
    cops_django_s_setup_reverse_proxy_dvhost:      "{{cops_django_s_setup_reverse_proxy_dvhost     |default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_reverse_proxy_vhost:       "{{cops_django_s_setup_reverse_proxy_vhost      |default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_reverse_proxy_front_vhost: "{{cops_django_s_setup_reverse_proxy_front_vhost|default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_reverse_proxy_users:       "{{cops_django_s_setup_reverse_proxy_users      |default(cops_django_s_setup_reverse_proxy|default(cops_django_s_setup|default(cops_django_lifecycle_app_setup|default(not only_steps))))}}"
    cops_django_s_setup_django_statics: "{{cops_django_s_setup_django_statics|default(cops_django_s_setup_django|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_setup_django_locales: "{{cops_django_s_setup_django_locales|default(cops_django_s_setup_django|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_setup_venv: "{{(
      cops_django_s_setup_venv_venv or
      cops_django_s_setup_venv_buildpy or
      cops_django_s_setup_venv_requirements)}}"
    cops_django_s_reverse_proxy_install:                  "{{cops_django_s_reverse_proxy_install                               |default(cops_django_s_reverse_proxy|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_reverse_proxy_reload:                   "{{cops_django_s_reverse_proxy_reload                                |default(cops_django_s_reverse_proxy|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_manage_content_migrate:                 "{{cops_django_s_manage_content_migrate                              |default(cops_django_s_manage_content|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_manage_content_create_admins:           "{{cops_django_s_manage_content_create_admins                        |default(cops_django_s_manage_content|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_manage_content_syncdb_only_first_time:  "{{cops_django_s_manage_content_syncdb_only_first_time               |default(cops_django_s_manage_content|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_manage_content_reset_site:              "{{cops_django_s_manage_content_reset_site                           |default(False)}}"
    cops_django_s_manage_content_syncdb:              "{{cops_django_s_manage_content_syncdb                           |default(False)}}"
    cops_django_s_users_user:     "{{cops_django_s_users_user   |default(cops_django_s_users|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_users_group:    "{{cops_django_s_users_group  |default(cops_django_s_users|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_workers_service: "{{cops_django_s_workers_service |default(cops_django_s_workers|default(cops_django_lifecycle_app_setup|default(not only_steps)))}}"
    cops_django_s_healthchecks:  "{{cops_django_s_healthchecks  |default(cops_django_lifecycle_app_setup|default(not only_steps))}}"
    cops_django_s_fixperms_configs:   "{{cops_django_s_fixperms_configs|default((cops_django_s_first_fixperms|default(not only_steps)) or (cops_django_s_end_fixperms|default(not only_steps)))}}"
    cops_django_s_fixperms_run:       "{{cops_django_s_fixperms_run    |default((cops_django_s_first_fixperms|default(not only_steps)) or (cops_django_s_end_fixperms|default(not only_steps)))}}"
- set_fact:
    cacheable: false
    cops_django_s_first_fixperms: "{{cops_django_s_first_fixperms        |default(cops_django_s_fixperms_configs or cops_django_s_fixperms_run)}}"
    cops_django_s_end_fixperms:   "{{cops_django_s_end_fixperms          |default(cops_django_s_fixperms_configs or cops_django_s_fixperms_run)}}"
    cops_django_s_setup_django:       "{{(
        cops_django_s_setup_django_statics or
        cops_django_s_setup_django_locales)}}"
    cops_django_s_manage_content:       "{{(
      cops_django_s_manage_content_syncdb or
      cops_django_s_manage_content_migrate or
      cops_django_s_manage_content_create_admins or
      cops_django_s_manage_content_syncdb_only_first_time or
      cops_django_s_manage_content_reset_site)}}"
    cops_django_s_users:          "{{cops_django_s_users_user or cops_django_s_users_group}}"
    cops_django_s_layout:         "{{cops_django_s_layout_layout}}"

    cops_django_s_prerequisites:  "{{(
      cops_django_s_prerequisites_supervisor or
      cops_django_s_prerequisites_build_pkgs or
      cops_django_s_prerequisites_pkgs)}}"
    cops_django_s_workers:        "{{cops_django_s_workers       |default(cops_django_lifecycle_app_setup|default(not only_steps))}}"
    cops_django_s_entry_point:    "{{cops_django_s_entry_point   |default(ansible_virtualization_type in ['docker'] and not only_steps)}}"
    cops_django_s_setup_front:  "{{(
      cops_django_s_setup_front_build or
      cops_django_s_setup_front_sync)}}"
    cops_django_s_setup_reverse_proxy:  "{{(
      cops_django_s_setup_reverse_proxy_dvhost or
      cops_django_s_setup_reverse_proxy_vhost or
      cops_django_s_setup_reverse_proxy_users)}}"
    cops_django_s_reverse_proxy:  "{{(cops_django_s_reverse_proxy_reload or cops_django_s_reverse_proxy_install)}}"
- set_fact:
    cacheable: false
    cops_django_s_setup: "{{(
        cops_django_s_setup_configs or
        cops_django_s_setup_supervisor or
        cops_django_s_setup_venv or
        cops_django_s_setup_front or
        cops_django_s_setup_hosts or
        cops_django_s_setup_app or
        cops_django_s_setup_django or
        cops_django_s_setup_reverse_proxy)}}"
- set_fact:
    cacheable: false
    cops_django_lifecycle_app_level_1_steps: "{{(
        cops_django_s_users or
        cops_django_s_layout or
        cops_django_s_first_fixperms or
        cops_django_s_prerequisites or
        cops_django_s_setup or
        cops_django_s_reverse_proxy or
        cops_django_s_workers or
        cops_django_s_healthchecks or
        cops_django_s_entry_point or
        cops_django_s_manage_content or
        cops_django_s_end_fixperms)}}"
- set_fact:
    cacheable: false
    cops_django_lifecycle_app_setup: "{{cops_django_lifecycle_app_setup|default(
                                          (cops_django_lifecycle_app|default(False)) or (
                                            cops_django_lifecycle_app_level_1_steps))}}"
    cops_django_lifecycle_app_push_code: "{{cops_django_lifecycle_app_push_code|default(cops_django_lifecycle_app|default(not only_steps))}}"
- set_fact:
    cacheable: false
    cops_django_lifecycle_app: "{{cops_django_lifecycle_app|default(
        cops_django_lifecycle_app_push_code or
        cops_django_lifecycle_app_setup)}}"
- set_fact:
    cacheable: false
    cops_django_lifecycle_lc_1_steps: "{{(
      cops_django_lifecycle_ftp or
      cops_django_lifecycle_db or
      cops_django_lifecycle_dbbackup or
      cops_django_lifecycle_app)}}"
- set_fact:
    cacheable: false
    cops_django_s_vars: "{{cops_django_s_vars|default(cops_django_lifecycle_lc_1_steps)}}"
