# build layout, install base pkgs and virtualenv with bare minimum working copy
ADD . /provision_dir
RUN .ansible/scripts/setup_core_variables.sh
RUN ROLES="django_push_code django_users django_layout django_fixperms" $_call_roles
RUN ROLES="django_prerequisites" $_call_roles
