# build layout, install base pkgs and virtualenv with bare minimum working copy
ADD . /provision_dir
RUN ROLES="django_push_code django_users django_layout django_fixperms" $_call_roles
RUN ROLES="django_setup_venv" $_call_roles
